### ISSUE TITLE
$_POST/$_FILE compatible body parsing

### ISSUE THREAD

**Issue by brstgt** [amphp/http-server#179]
I dont know if this has ever been discussed before. Maybe it would be helpful for people to migrate to aerys if there is a way to parse a post body in a backwards compatible way to create $_POST/$_FILES'ish data.

It could be either done by extending BodyParser or by implementing a wrapper that takes a parsed body and returns a $_POST'ish or $_FILES'ish result.

**Comment by kelunik** [comment]
We have implemented something like that for PHP-PM, but `$_FILES` doesn't work with arrays there, yet. Emulating it so that `move_uploaded_file()` and `is_uploaded_file()` work is unfortunately impossible as it seems.

https://github.com/kelunik/php-pm-httpkernel/blob/c4e09259dafbdc8dd531d9d8f483d894278fefbf/Bridges/HttpKernel.php#L164-L203

**Comment by kelunik** [comment]
I'm going to close this, as there's currently no interest in building this from our side. The body parsing moved to https://github.com/amphp/http-server-form-parser in the meantime, a separate package can be built with another parsing result. Interested people can find a PoC implementation in the above link.
