### ISSUE TITLE
Request / Response final?

### ISSUE THREAD

**Issue by kelunik** [amphp/http-server#235]
Should we make `Request` / `Response` `final`?

**Comment by kelunik** [comment]
@trowski Thoughts?

Only reason to make it not final would be allowing `new JsonResponse` IMO, but people can also use a function or static method instead like `JsonResponse::create()`.

**Comment by tschallacka** [comment]
My 2 cents:
The incoming Request should be final. Would be weird if something could remove essential request parameters from a request that something else might need later on.

 A response should be mutable because various entities might wish to add things/modify things to a response, for example a plugin that wraps a html response into a json response.

**Comment by kelunik** [comment]
@tschallacka This issue isn't about things being mutable or not, it's about users being able to extend the classes or not.

**Comment by mega6382** [comment]
If you are thinking about not making it `final` just for rendering Json, then there is no need. Because that can be achieved via many other ways. Or you can just add a method in the `Response` class rendering Json, but I get it that there is not much point to that either.

**Comment by mega6382** [comment]
Yeah, I guess a helper function can easily be used for that. So, I guess there is no need for not making the classes final.
