### ISSUE TITLE
Hello World example is broken.

### ISSUE THREAD

**Issue by ro70** [amphp/http-server#268]
Starting the example in
```
http-server/examples/hello-world.php 
```
throws
```
PHP Fatal error:  Uncaught Error: Class 'Amp\Log\StreamHandler' not found in ...
```
Can you fix this please?

"amphp/http-server": "^0.8.2"

**Comment by kelunik** [comment]
The examples aren't runnable if this package is installed as a Composer dependency, as they require additional dependencies that are listed in `"require-dev"`. Please clone the repository on its own and run `composer install` to run the examples.

I've excluded the `examples` directory in case the package is installed via Composer, because they won't work anyway.

**Comment by ro70** [comment]
@kelunik Thank you very much. After I cloned the repository and installed a few php packages ( `php7.0-xml, php7.0-mbstring, php7.0-curl, php7.0-intl)` the examples work.

**Comment by kelunik** [comment]
@ro70 Did you really need all those?

**Comment by kelunik** [comment]
@ro70 Only for that project or is that a message thrown by Composer itself?
